global using Application.Common.Interfaces;
global using Application.Common.Services;
global using Application.Common.Settings;
global using Application.Features.Environments.Queries.GetEnvironmentById;
global using BusinessMakerFramework.Application.Common.Contracts;
global using BusinessMakerFramework.Application.Common.Contracts.Interfaces;
global using BusinessMakerFramework.Domain.Core.Exceptions;
global using BusinessMakerFramework.Shared.Utilities.Utilities;
global using Domain.Aggregates.ApiTokenAggregate;
global using Domain.Aggregates.ChangeRequestAggregate;
//global using SystemEnvironment = System.Environment;
global using Domain.Aggregates.FeatureAggregate;
global using Domain.Aggregates.ProjectAggregate;
global using Domain.Aggregates.UserAggregate;
global using Domain.Enums;
global using FluentValidation;
global using Mapster;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using Environment = Domain.Aggregates.EnvironmentAggregate.Environment;
